; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
framework = espidf
monitor_filters = esp32_exception_decoder
extra_scripts = 
    pre:auto_firmware_version.py
    scripts/generate_data_profiles.py
    scripts/generate_ha_profiles.py
board_build.sdkconfig_defaults = sdkconfig.defaults

build_flags =
    -DESP32=1
board_build.embed_txtfiles =
    static/root.html
    static/config.html
    static/status.html
    static/upgrade.html
    static/adc.html
    static/common.css
    static/common.js
    static/commands.html
    static/cron.html
    static/devices.html
    static/logs.html
    static/metrics.html
    static/values.html

[env:esp32-c3]
platform = espressif32@6.13.0
board = esp32-c3-devkitm-1
board_build.partitions = min_spiffs.csv
build_flags =
    ${env.build_flags}
    -DRESET_PIN=20
    -DPWM_PIN=6

monitor_filters = esp32_exception_decoder
lib_deps = 
    ${env.lib_deps}
    https://github.com/yuhu-/ebus.git#f5c73b961af1ff021d5fc7014dbc4a5a010d542f

[env:esp32-c3-ota]
extends = env:esp32-c3
upload_port = esp-ebus.local
upload_protocol = espota

[env:esp32-c3-internal]
extends = env:esp32-c3

build_flags =
    ${env.build_flags}
    -DRESET_PIN=20
    -DPWM_PIN=6
    # App specific
    -DCOMMAND_CAPACITY=96                   # Maximum number of read / passive commands to store
    -DCOMMAND_MAX_FIELDS=4                  # Max fields per command
    -DWRITE_CMD_CAPACITY=16                 # Max commands with write_cmd (separate storage)
    -DOVERRIDE_FIELD_CAPACITY=16            # Max commands with overrided fields
    # EBUS Library
    -DEBUS_INTERNAL=1                       # Enable ebus library
    -DEBUS_MINIMAL_DIAGNOSTICS=1            # Cut off ebus library diagnostics
    # Component Layer
    -DEBUS_HANDLER_HISTORY_SIZE=1           # Number of Handler FSM transition history tracking
    -DEBUS_REQUEST_HISTORY_SIZE=1           # Number of Request FSM transition history tracking
    # Orchestration Layer
    -DEBUS_REACTOR_STACK_SIZE=4096          # Stack size for Reactor thread
    -DEBUS_REACTOR_PRIORITY=5               # Priority for Reactor thread
    -DEBUS_BUS_STACK_SIZE=3072              # Stack size for Bus
    -DEBUS_BUS_PRIORITY=15                  # Priority for Bus thread
    -DEBUS_CLIENT_MANAGER_STACK_SIZE=4096   # Stack size for Client Manager thread
    -DEBUS_CLIENT_MANAGER_PRIORITY=12       # Priority for Client Manager thread
    # Diagnostics Layer
    -DEBUS_UTILIZATION_HISTORY_SIZE=1       # Number of utilization entries to keep in memory
    -DEBUS_ERROR_HISTORY_SIZE=1             # Number of error entries to keep in memory
    -DEBUS_TRACE_HISTORY_SIZE=1             # Number of trace events to keep in memory
    # Networking Layer
    -DEBUS_CLIENT_BUS_QUEUE_SIZE=16         # Size of the client bus event queue
    -DEBUS_MAX_CLIENTS=2                    # Maximum number of network bridge clients
    # Application Layer
    -DEBUS_SIGNAL_QUEUE_SIZE=16             # Size of the reactor signal queue
    -DEBUS_PROTOCOL_QUEUE_SIZE=8            # Size of the protocol event queue
    -DEBUS_BUS_QUEUE_SIZE=16                # Size of the bus event queue
    -DEBUS_MAX_DEVICES=16                   # Maximum number of devices to manage
    -DEBUS_SCHEDULER_MAX_ITEMS=8            # Size of the scheduler queue
    -DEBUS_POLL_MAX_ITEMS=64                # Size of the poll queue
    -DEBUS_POLL_CAPACITY=24                 # Capacity for poll command sequences

[env:esp32-c3-internal-simulation]
extends = env:esp32-c3-internal
build_flags = 
    ${env:esp32-c3-internal.build_flags}
    -DEBUS_SIMULATION=1
    -DEBUS_BUS_SYN_STACK_SIZE=1024          # Stack size for Bus SYN thread
    -DEBUS_BUS_SYN_PRIORITY=3               # Priority for Bus SYN thread

[env:esp32-c3-internal-ota]
extends = env:esp32-c3-internal
upload_port = esp-ebus.local
upload_protocol = espota

[env:esp32-c3-internal-remote]
extends = env:esp32-c3-internal
extra_scripts =
    ${env.extra_scripts}
    upload_http_pio.py

upload_protocol = custom
upload_port = esp-ebus-remote.test # configured in hosts file
custom_upload_user = admin
custom_upload_password = ebusebus
