#!/usr/bin/env python3
"""
Pre-build script for PlatformIO.
Writes include/app/build_info_gen.hpp with the current build timestamp, so
the firmware build stamp always reflects the link time (unlike __DATE__ /
__TIME__, which only update when their translation unit recompiles).
Only system_api.cpp includes it, keeping rebuild churn to one TU.
"""

import os
import time

try:
    Import("env")
    PROJECT_ROOT = os.path.dirname(env["PROJECT_SRC_DIR"])
except NameError:
    SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
    PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)

OUTPUT_FILE = os.path.join(PROJECT_ROOT, "include", "app",
                           "build_info_gen.hpp")


def main():
    now = int(time.time())
    utc = time.strftime("%Y-%m-%d %H:%M:%S", time.gmtime(now))
    content = (
        "#pragma once\n"
        "// Auto-generated by scripts/generate_build_info.py at build time.\n"
        "// Do not edit. Git-ignored.\n"
        f'inline constexpr long long build_epoch = {now}LL;\n'
        f'inline constexpr char build_time_str[] = "{utc}";\n'
    )
    with open(OUTPUT_FILE, "w") as f:
        f.write(content)


# Called unconditionally (not under __main__): PlatformIO exec()s
# extra_scripts, so __name__ is never "__main__" there.
main()
